---
deploy:
  tasks:
    - export DEPLOYPATH=/home/didm/repositories/didm
    - /bin/cp -R * $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --working-dir $DEPLOYPATH
    - /usr/bin/php $DEPLOYPATH/artisan migrate --force
    - /usr/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/bin/php $DEPLOYPATH/artisan route:cache
    - /bin/touch $DEPLOYPATH/storage/logs/laravel.log
